# -- The Environment variable. It accepts: 'kuberentes-athens', 'kuberentes-uma', 'openshift'
environment: "openshift"

# -- If env: 'kuberentes-athens' or env: 'kuberentes-uma', use the Ip address dude for the kubernetes to your Ingress Controller ej: kubectl -n NAMESPACE_CAPIF get ing s
ingress_ip: 
    athens: "10.161.1.126"
    uma: "10.11.23.49"

dbnetapp:
  netapppostgres:
    # -- The docker image repository to use
    image:
      repository: "709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5gvalidation:fogusnetapp-netapppostgres"
      # -- The docker image tag to use
      # -- @default Chart version
      tag: "latest"
    resources:
     limits:
       cpu: 100m
       memory: 128Mi
     requests:
       cpu: 100m
       memory: 128Mi
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  type: ClusterIP
  replicas: 1
django:
  netappdjango:
    # -- The docker image repository to use
    image:
      repository: "709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5gvalidation:fogusnetapp-netappdjango"
      # -- The docker image tag to use
      # -- @default Chart version
      tag: "latest"
    resources:
     limits:
       cpu: 100m
       memory: 128Mi
     requests:
       cpu: 100m
       memory: 128Mi
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  replicas: 1
  type: ClusterIP
env:
  environment: production
  callbackAddress: https://my-fogus.apps.ocp-epg.hi.inet
  capifHostname: "my-capif.apps.ocp-epg.hi.inet"
  capifPortHttp: "30048"
  capifPortHttps: "30548"
  frontendAddress: my-fogus.apps.ocp-epg.hi.inet
  nefAddress: my-nef.apps.ocp-epg.hi.inet
  nefPassword: pass
  nefUser: admin@my-email.com
  netappAddress: 192.168.1.5:8000
  pathToCerts: /code/capif_onboarding
  postgresDb: evolvedb
  postgresPassword: evolvepass
  postgresUser: evolveclient
  vappAddress: 195.134.66.79:8443
netapp:
  netappfe:
    # -- The docker image repository to use
    image:
      repository: "709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5gvalidation:fogusnetapp-netappfe"
      # -- The docker image tag to use
      # -- @default Chart version
      tag: "latest"
    resources: {}
#     limits:
#       cpu: 100m
#       memory: 128Mi
#     requests:
#       cpu: 100m
#       memory: 128Mi
  ports:
  - name: "fe"
    port: 4200
    targetPort: 4200
  replicas: 1
  type: ClusterIP
kubernetesClusterDomain: cluster.local
