
# -- The Environment variable. It accepts: 'kuberentes-athens', 'kuberentes-uma', 'openshift'
environment: "openshift"

# pipeline. It accepts: validation, certification or verification
pipeline: verification

# -- If env: 'kuberentes-athens' or env: 'kuberentes-uma', use the Ip address dude for the kubernetes to your Ingress Controller ej: kubectl -n NAMESPACE_CAPIF get ing s
ingress_ip: 
    athens: "10.161.1.126"
    uma: "10.11.23.49"
    cosmote: "172.25.2.100"

env:
  environmentMode: production
  tsnAddress: my-tsn.apps.ocp-epg.hi.inet
  frontendAddress: my-immersion.apps.ocp-epg.hi.inet
  callbackAddress: "app:5000"
  capifHostname: my-capif.apps.ocp-epg.hi.inet
  capifPortHttp: 30048
  capifPortHttps: 30548
  nefAddress: my-nef.apps.ocp-epg.hi.inet
  nefUser: "admin@my-email.com"
  nefPassword: "pass"
  pathToCerts: "/zortenet_netapp/capif_onboarding"

netapp:
  zorteNetapp:
    # -- The docker image repository to use
    image:
      # -- The docker image tag to use
      # -- @default Chart version
      tag: "zortenetnetapp-zorte_netapp"
  ports:
  - name: "app"
    port: 5000
    targetPort: 5000
  replicas: 1
  type: ClusterIP

kubernetesClusterDomain: cluster.local
