apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o dummy-netapp
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: python-netapp
  name: python-netapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: python-netapp
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -o dummy-netapp
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/demo-network: "true"
        io.kompose.service: localization-netapp
    spec:
      containers:
        - image: dockerhub.hi.inet/evolved-5g//evolved-5g/localizationnetapp:latest
          name: python-netapp
          resources: {}
      restartPolicy: Always
status: {}
