apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml -c -o folder
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: infolysis-netapp
  name: infolysis-netapp
spec:
  ports:
    - name: frontend-config
      port: 80
      targetPort: 80
    - name: netapp-controller
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: infolysis-netapp
status:
  loadBalancer: {}
