## variables for the CAPIF
capif_hostname: capif.apps.ocp-epg.hi.inet
NET_APP_NAME: test
NET_API_PROT: http
NET_API_ADDRESS: 192.168.202.35:8888
NET_API_USER: admin@my-email.com
NET_API_PASS: pass
CALLBACK_ADDRESS: 192.168.202.35:80
COLLECTOR_HOST: https://evolved5g-collector.qmon.eu
COLLECTOR_USER: test
COLLECTOR_PASS: test
MN_HOST: http://evolved5g-mn.qmon.eu
MN_TOKEN: d074feb62430a78e49b5a6da58cb81827e4229b9e3a4ecb28d2a3e47469871247e15ab95a9f34ac713682cebee1031c4da3a
CAPIF_PATH: /app/capif_onboarding/
CAPIF_HOSTNAME: capifcore
CAPIF_PORT_HTTP: "80"
CAPIF_PORT_HTTPS: "443"
CAPIF_CALLBACK_ADDRESS: =http://localhost:5000