apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    io.kompose.service: postgres
  {{- include "8bells.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.28.0 (c4137012e)
spec:
  type: {{ .Values.postgres.type }}
  selector:
    io.kompose.service: postgres
  {{- include "8bells.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.postgres.ports | toYaml | nindent 2 -}}