## variables for the CAPIF
env: openshift
# mktp_hostname: marketplace.evolved-5g.eu
mktp_hostname: marketplace-pro.evolved-5g.eu
db_name: evolved5g_db
db_user: admin
db_password: secret
mktp_db_service: mktp-db
mktp_php_service: mktp-php
mktp_phpmyadmin_service: mktp-phpmyadmin
