apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o fogus
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: uma-netapp
  name: uma-netapp
spec:
  replicas: {{ .Values.app_replicas }}
  selector:
    matchLabels:
      io.kompose.service: uma-netapp
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -o fogus
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: uma-netapp
    spec:
      containers:
        - env:
            - name: NEFHOST
              value: http://evol5-capif-nef.apps.ocp-epg.hi.inet
          name: uma-netapp
          image: dockerhub.hi.inet/evolved-5g/testnetapp-netapp:latest
          ports:
            - containerPort: 10001
          resources: {}
      restartPolicy: Always

status: {}
