apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o fogus
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-container
  name: postgres-container
spec:
  selector:
    matchLabels:
      io.kompose.service: postgres-container
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -o fogus
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: postgres-container
    spec:
    {{- if or (eq .Values.env "kubernetes-athens") (eq .Values.env "kubernetes-uma") }}
      imagePullSecrets:
        - name: regcred
      {{- end }}
      containers:
        {{- if or (eq .Values.env "kubernetes-athens") (eq .Values.env "kubernetes-uma") }}
        - image: 709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:umacsictest-postgres_container-latest
        {{- else }}
        - image: dockerhub.hi.inet/evolved-5g/umacsictest/umacsictest-postgres_container:latest
        {{- end }}
          name: postgres-container
          ports:
            - containerPort: 5433
          resources: {}
      restartPolicy: Always
status: {}
