# -- The Environment variable. It accepts: 'kuberentes-athens', 'kuberentes-uma', 'openshift'
environment: "openshift"

# -- If env: 'kuberentes-athens' or env: 'kuberentes-uma', use the Ip address dude for the kubernetes to your Ingress Controller ej: kubectl -n NAMESPACE_CAPIF get ing s
ingress_ip: 
    athens: "10.161.1.126"
    uma: "10.11.23.49"
    cosmote: "172.25.2.100"

env:
  frontendAddress: "my-teleop.apps.ocp-epg.hi.inet"
  capifCallbackUrl: "http://localhost:5000"
  capifHostname: "my-capif.apps.ocp-epg.hi.inet"
  capifPortHttp: "30048"
  capifPortHttps: "30548"
  nefAddress: my-nef.apps.ocp-epg.hi.inet
  nefUser: admin@my-email.com
  nefPassword: pass

netapp:
  teleopNetapp:
    # -- The docker image repository to use
    image:
      repository: "709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:teleopnetapp"
      # -- The docker image tag to use
      # -- @default Chart version
      tag: ""
  ports:
  - name: "netapp"
    port: 5000
    targetPort: 5000
  replicas: 1
  type: ClusterIP