apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "immersion.fullname" . }}-netapp
  labels:
    io.kompose.service: imm-netapp
  {{- include "immersion.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.28.0 (c4137012e)
spec:
  replicas: {{ .Values.netapp.replicas }}
  selector:
    matchLabels:
      io.kompose.service: imm-netapp
    {{- include "immersion.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        io.kompose.network/nef-emulator-default: "true"
        io.kompose.service: imm-netapp
      {{- include "immersion.selectorLabels" . | nindent 8 }}
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.28.0 (c4137012e)
    spec:
      imagePullSecrets:
        - name: regcred
      {{- if eq .Values.environment "kubernetes-athens" }}
      hostAliases:
        - ip: "{{ .Values.ingress_ip.athens }}"
          hostnames:
            - "{{ .Values.env.capifHostname }}"
            - "{{ .Values.env.nefAddress }}"
            - "{{ .Values.env.tsnAddress }}"
      {{- end }}
      {{- if eq .Values.environment "kubernetes-cosmote" }}
      hostAliases:
        - ip: "{{ .Values.ingress_ip.cosmote }}"
          hostnames:
            - "{{ .Values.env.capifHostname }}"
            - "{{ .Values.env.nefAddress }}"
            - "{{ .Values.env.tsnAddress }}"
      {{- end }}
      {{- if eq .Values.environment "kubernetes-uma" }}
      hostAliases:
        - ip: "{{ .Values.ingress_ip.uma }}"
          hostnames:
            - "{{ .Values.env.capifHostname }}"
            - "{{ .Values.env.nefAddress }}"
            - "{{ .Values.env.tsnAddress }}"
      {{- end }}
      containers:
      - env:
        - name: ENVIRONMENT_MODE
          value: {{ quote .Values.env.environmentMode }}
        - name: CAPIF_HOSTNAME
          value: {{ quote .Values.env.capifHostname }}
        - name: CAPIF_PORT_HTTP
          value: {{ quote .Values.env.capifPortHttp }}
        - name: CAPIF_PORT_HTTPS
          value: {{ quote .Values.env.capifPortHttps }}
        - name: PATH_TO_CERTS
          value: {{ quote .Values.env.pathToCerts }}
        - name: NEF_CALLBACK_URL
          value: http://{{ .Values.env.nefAddress }}
        - name: CALLBACK_ADDRESS
          value: http://{{ .Values.env.frontendAddress }}
        - name: FRONTEND_CALLBACK_ADDRESS
          value: {{ quote .Values.env.frontendAddress }}
        - name: NEF_ADDRESS
          value: {{ quote .Values.env.nefAddress }}
        - name: NEF_USER
          value: {{ quote .Values.env.nefUser }}
        - name: NEF_PASSWORD
          value: {{ quote .Values.env.nefPassword }}
        - name: NETAPP_ID
          value: {{ quote .Values.env.netappId }}
        - name: NETAPP_IP
          value: {{ quote .Values.env.netappIp }}
        - name: NETAPP_NAME
          value: {{ quote .Values.env.netappName }}
        - name: NETAPP_PORT_5G
          value: {{ quote .Values.env.netappPort5G }}
        - name: NETAPP_PORT_VAPP
          value: {{ quote .Values.env.netappPortVapp }}
        - name: NETAPP_PORT_WEB
          value: {{ quote .Values.env.netappPortWeb }}
        - name: NETAPP_SERVER_VAPP
          value: {{ quote .Values.env.netappServerVapp }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        {{- if eq .Values.pipeline "verification" }}
        image: {{- include "immersion.baseRepo" . }}:{{ .Values.netapp.immNetappContainer.image.tag }}-{{ .Chart.AppVersion }}
        {{- else }}
        image: {{- include "immersion.baseRepo" . }}{{- include "immersion.pipeline" . }}:{{ .Values.netapp.immNetappContainer.image.tag }}-{{ .Chart.AppVersion }}
        {{- end }}
        imagePullPolicy: Always
        name: imm-netapp-container
        ports:
        - containerPort: 9876
        - containerPort: 9877
        - containerPort: 9998
        - containerPort: 9999
        resources: {}
      restartPolicy: Always