# -- The Environment variable. It accepts: 'kuberentes-athens', 'kuberentes-uma', 'openshift'
environment: "openshift"

# pipeline. It accepts: validation, certification or verification
pipeline: verification

# -- If env: 'kuberentes-athens' or env: 'kuberentes-uma', use the Ip address dude for the kubernetes to your Ingress Controller ej: kubectl -n NAMESPACE_CAPIF get ing s
ingress_ip: 
    athens: "10.161.1.126"
    uma: "10.11.23.49"
    cosmote: "172.25.2.100"

env:
  tsnAddress: my-tsn.apps.ocp-epg.hi.inet
  environmentMode: production
  frontendAddress: "my-gmi.apps.ocp-epg.hi.inet"
  capifCallbackUrl: "http://localhost:5000"
  capifHostname: "my-capif.apps.ocp-epg.hi.inet"
  capifPortHttp: "30048"
  capifPortHttps: "30548"
  nefAddress: my-nef.apps.ocp-epg.hi.inet
  nefCallbackUrl: "http://my-nef.apps.ocp-epg.hi.inet/monitoring/callback"
  nefUser: "admin@my-email.com"
  nefPassword: "pass"
  netappId: "gmi_netapp"
  netappName: "GMI_Netapp"
  netappPath: "/src"
  netappPortVapp: 8383
  pathToCerts: "/code/src/capif_onboarding"
  ueRequestedIp: "10.0.0.1"

netapp:
  gmiNetappContainer:
    image:
      # -- The docker image tag to use
      # -- @default Chart version
      tag: "gmiaeronetapp-gmi_netapp_container"
  ports:
  - name: "netapp"
    port: 8383
    targetPort: 8383
  replicas: 1
  type: ClusterIP
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 128Mi
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

kubernetesClusterDomain: cluster.local
