apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: capif-callback-server
  name: capif-callback-server
spec:
  ports:
    - name: "http-capif"
      port: 80
      targetPort: 8080
    - name: "https-capif"
      port: 443
      targetPort: 443
  selector:
    io.kompose.service: capif-callback-server
status:
  loadBalancer: {}
