apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: nef-callback-server
  name: nef-callback-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nef-callback-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/demo-network: "true"
        io.kompose.service: nef-callback-server
    spec:
      containers:
        - env:
            - name: CAPIF_CALLBACK_PORT
              valueFrom:
                configMapKeyRef:
                  key: CAPIF_CALLBACK_PORT
                  name: env
            - name: CAPIF_CALLBACK_URL
              valueFrom:
                configMapKeyRef:
                  key: CAPIF_CALLBACK_URL
                  name: env
            - name: CAPIF_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: CAPIF_HOSTNAME
                  name: env
            - name: CAPIF_PORT
              valueFrom:
                configMapKeyRef:
                  key: CAPIF_PORT
                  name: env
            - name: CAPIF_PORT_HTTPS
              valueFrom:
                configMapKeyRef:
                  key: CAPIF_PORT_HTTPS
                  name: env
            - name: NEF_CALLBACK_IP
              valueFrom:
                configMapKeyRef:
                  key: NEF_CALLBACK_IP
                  name: env
            - name: NEF_CALLBACK_PORT
              valueFrom:
                configMapKeyRef:
                  key: NEF_CALLBACK_PORT
                  name: env
            - name: NEF_IP
              valueFrom:
                configMapKeyRef:
                  key: NEF_IP
                  name: env
            - name: NEF_PASS
              valueFrom:
                configMapKeyRef:
                  key: NEF_PASS
                  name: env
            - name: NEF_PORT
              valueFrom:
                configMapKeyRef:
                  key: NEF_PORT
                  name: env
            - name: NEF_USER
              valueFrom:
                configMapKeyRef:
                  key: NEF_USER
                  name: env
            - name: PATH_TO_CERTS
              valueFrom:
                configMapKeyRef:
                  key: PATH_TO_CERTS
                  name: env
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  key: REDIS_HOST
                  name: env
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  key: REDIS_PORT
                  name: env
            - name: REQUESTS_CA_BUNDLE
              valueFrom:
                configMapKeyRef:
                  key: REQUESTS_CA_BUNDLE
                  name: env
            - name: SSL_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  key: SSL_CERT_FILE
                  name: env
            - name: TSN_IP
              valueFrom:
                configMapKeyRef:
                  key: TSN_IP
                  name: env
            - name: TSN_PORT
              valueFrom:
                configMapKeyRef:
                  key: TSN_PORT
                  name: env
          image: nef_callback_server
          name: nef-callback-server
          ports:
            - containerPort: 8080
            - containerPort: 443
          resources: {}
      restartPolicy: Always
status: {}
