apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: redis-db
  name: redis-db
  namespace: dummy-network-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/demo-network: "true"
        io.kompose.service: redis-db
    spec:
      containers:
        - image: redis:latest
          name: redis-db
          resources: {}
      restartPolicy: Always
status: {}
