apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: redis-db
  name: redis-db
spec:
  ports:
    - name: "redis"
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: redis-db
status:
  loadBalancer: {}
