environment: "openshift"
ingress_ip: 
    athens: "10.161.1.126"
    uma: "10.11.23.49"

adminer:
  NetappAdminer:
    image:
      repository: 709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:8bellsnetapp-8b_netapp_adminer
      tag: ""
  env:
    adminerPassword: "1234"
    adminerPortOne: "8008"
    adminerPortTwo: "8080"
  ports:
  - name: "8008"
    port: 8008
    targetPort: 8080
  replicas: 1
  type: ClusterIP
env:
  capifHostname: "my-capif.apps.ocp-epg.hi.inet"
  capifPortHttp: "8080"
  capifPortHttps: "443"
  nefAddress: "my-nef.apps.ocp-epg.hi.inet"
  frontendAddress: "netapp.app.ocp-epg.hi.inet"
  host: 172.17.0.1
  hostUrl: http://172.17.0.1
  vappIp: 10.10.10.40
  vappPass: admin8b
  vappUser: admin8b
kubernetesClusterDomain: cluster.local

fe:
  replicas: 1
netapp:
  Netapp:
    image:
      repository: 709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:8bellsnetapp-8b_netapp
      tag: ""
  env:
    callbackAddress:  http://172.17.0.1:5000/monitoring/callback:5000
    callbackAdr: http://172.17.0.1:5000/monitoring/callback
    nefPassword: pass
    nefPort: 4443
    nefUser: "admin@my-email.com"
    netappIp: http://172.17.0.1:5000
    netappName: myNetapp
    netappPort: "5000"
    vappIp: "10.10.10.40"
    vappPass: "admin8b"
    vappUser: "admin8b"
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  type: ClusterIP
postgres:
  NetappDb:
    image:
      repository: 709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:8bellsnetapp-8b_netapp_db
      tag: ""  
  env:
    postgresPassword: postgres
    postgresDb: postgres
    postgresPort: "5432"
    postgresUsername: postgres
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  replicas: 1
  type: ClusterIP
