apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o fogus
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: dbnetapp
  name: dbnetapp
spec:
  replicas: {{ .Values.app_replicas }}
  selector:
    matchLabels:
      io.kompose.service: dbnetapp
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -o fogus
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: dbnetapp
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: evolvedb
            - name: POSTGRES_PASSWORD
              value: evolvepass
            - name: POSTGRES_USER
              value: evolveclient
          name: dbnetapp
          image: dockerhub.hi.inet/evolved-5g/fogusnetapp-netapppostgres:latest
          ports:
            - containerPort: 5432
          resources: {}
      restartPolicy: Always

status: {}
