apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o fogus
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: netappfe
  name: netappfe
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: netappfe
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -o fogus
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: netappfe
    spec:
      containers:
        - image: dockerhub.hi.inet/evolved-5g/fogusnetapp-netappfe:latest
          name: netappfe
          ports:
            - containerPort: 4200
          resources: {}
      restartPolicy: Always

