apiVersion: batch/v1
kind: Job
metadata:
  name: db-init
  labels:
    io.kompose.network/nef-emulator-default: "true"
  {{- include "nef-kube.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      {{- if eq .Values.environment "kubernetes-athens" }}
      hostAliases: 
        - ip: "{{ .Values.ingress_ip.athens }}"
          hostnames:
            - "{{ .Values.backend.ingress.host }}"
            - "{{ .Values.env.capifHostname }}"
      {{- end }}
      {{- if eq .Values.environment "kubernetes-uma" }}
      hostAliases:
        - ip: "{{ .Values.ingress_ip.uma }}"
          hostnames:
            - "{{ .Values.backend.ingress.host }}"
            - "{{ .Values.env.capifHostname }}"
      {{- end }}
      containers:
      - name: db-init
        image: "{{ .Values.backend.backend.image.repository }}-{{ .Values.backend.backend.image.tag
          | default .Chart.AppVersion }}"
        command: ["/bin/bash", "-c"]
        args:
          - sleep 180;
            echo DOMAIN=$DOMAIN;
            echo NGINX_HTTPS=$NGINX_HTTPS;
            echo FIRST_SUPERUSER=$FIRST_SUPERUSER;
            echo FIRST_SUPERUSER_PASSWORD=$FIRST_SUPERUSER_PASSWORD;
            apt update;
            apt install -y jq;
            curl -v -k  https://$DOMAIN:$NGINX_HTTPS;
            sed -i -e "s/source .env//g" app/db/init_simple.sh;
            bash ./app/db/init_simple.sh;
        env:
        - name: DOMAIN
          valueFrom:
            configMapKeyRef:
              key: DOMAIN
              name: env
        - name: NGINX_HTTPS
          valueFrom:
            configMapKeyRef:
              key: NGINX_HTTPS
              name: env
        - name: FIRST_SUPERUSER
          valueFrom:
            configMapKeyRef:
              key: FIRST_SUPERUSER
              name: env
        - name: FIRST_SUPERUSER_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: FIRST_SUPERUSER_PASSWORD
              name: env
      restartPolicy: Never
  backoffLimit: 4