{{- if or (eq .Values.env "kubernetes-athens") (eq .Values.env "kubernetes-uma") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  labels:
  {{- include "nef-kube.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml -c -o folder
    kompose.version: 1.26.1 (HEAD)
spec:
  rules:
  - host: "{{ .Values.backend.ingress.host }}"
    http:
      paths:
      - backend:
          service:
            name: 'backend'
            port:
              number: 8888
        path: /
        pathType: Prefix
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    io.kompose.service: backend
  {{- include "nef-kube.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yml convert
    kompose.version: 1.28.0 (c4137012e)
spec:
  type: {{ .Values.backend.type }}
  selector:
    io.kompose.service: backend
  {{- include "nef-kube.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.backend.ports | toYaml | nindent 2 -}}