apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nef.fullname" . }}-ingress
  labels:
  {{- include "nef.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml -c -o folder
    kompose.version: 1.26.1 (HEAD)
spec:
  {{- if eq .Values.environment "kubernetes-athens" }}
  ingressClassName: nginx
  {{- end }}
  rules:
  - host: "{{ .Values.backend.ingress.host }}"
    http:
      paths:
      - backend:
          service:
            name: {{ include "nef.fullname" . }}-backend
            port:
              number: 80
        path: /
        pathType: Prefix
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nef.fullname" . }}-backend
  labels:
    io.kompose.service: backend
  {{- include "nef.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yml convert
    kompose.version: 1.28.0 (c4137012e)
spec:
  type: {{ .Values.backend.type }}
  selector:
    io.kompose.service: backend
  {{- include "nef.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.backend.ports | toYaml | nindent 2 -}}