apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nef.fullname" . }}-backend
  labels:
  {{- include "nef.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml -c -o folder
    kompose.version: 1.26.1 (HEAD)
spec:
  {{- if eq .Values.environment "kubernetes-athens" }}
  ingressClassName: nginx
  {{- end }}
  rules:
  - host: "{{ .Values.backend.ingress.host }}"
    http:
      paths:
      - backend:
          service:
            name: '{{ include "nef.fullname" . }}-backend'
            port:
              number: 80
        path: /
        pathType: Prefix
  {{- if eq .Values.environment "openshift" }}
  tls:
  - {}
  {{ else }}
  tls:
  - hosts:
    - {{ .Values.backend.ingress.host }}
    secretName: {{ include "nef.fullname" . }}-backend-http
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nef.fullname" . }}-backend
  labels:
  {{- include "nef.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.type }}
  selector:
    app: backend
  {{- include "nef.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.backend.ports | toYaml | nindent 2 -}}