{{- if eq .Values.env "openshift" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    io.kompose.service: backend
  name: backend
spec:
  host: "{{ .Values.backend.ingress.host }}"
  port:
    targetPort: backend-port
  to:
    kind: Service
    name: backend
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    host: "{{ .Values.backend.ingress.host }}"
    routerCanonicalHostname: router-default.apps.ocp-epg.hi.inet
{{- end }}