apiVersion: v1
kind: Service
metadata:
  name: {{ include "nef.fullname" . }}-db
  labels:
  {{- include "nef.labels" . | nindent 4 }}
spec:
  type: {{ .Values.db.type }}
  selector:
    app: db
  {{- include "nef.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.db.ports | toYaml | nindent 2 -}}