apiVersion: v1
kind: Service
metadata:
  name: nef-mongo
  labels:
  {{- include "nef.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mongo.type }}
  selector:
    app: nef-mongo
  {{- include "nef.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.mongo.ports | toYaml | nindent 2 -}}