apiVersion: v1
kind: Service
metadata:
  name: {{ include "nef.fullname" . }}-mongo-express
  labels:
  {{- include "nef.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mongoExpress.type }}
  selector:
    app: mongo-express
  {{- include "nef.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.mongoExpress.ports | toYaml | nindent 2 -}}