apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose-resolved.yaml -o marketplace
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: artisan
  name: artisan
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: artisan
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose-resolved.yaml -o marketplace
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/docker_evolved5g_net: "true"
        io.kompose.service: artisan
    spec:
      containers:
        - command:
            - php
            - /var/www/html/artisan
          image: artisan
          name: evolved5g-pilot-artisan
          resources: {}
      restartPolicy: Always

status: {}
