apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose-resolved.yaml -o marketplace
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: composer
  name: composer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: composer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose-resolved.yaml -o marketplace
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/docker_evolved5g_net: "true"
        io.kompose.service: composer
    spec:
      containers:
        - image: composer
          name: evolved5g-pilot-composer
          resources: {}
      restartPolicy: Always

status: {}
