apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml -c -o folder
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: immersion-netapp
  name: immersion-netapp
spec:
  ports:
    - name: netapp-port-5g
      port: {{ .Values.netapp_port_5g }}
      targetPort: {{ .Values.netapp_port_5g }}
    - name: netapp-port-web
      port: {{ .Values.netapp_port_web }}
      targetPort: {{ .Values.netapp_port_web }}
    - name: netapp-port-vapp
      port: {{ .Values.netapp_port_vapp }}
      targetPort: {{ .Values.netapp_port_vapp }}
  selector:
    io.kompose.service: immersion-netapp
status:
  loadBalancer: {}
