apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netapp
  labels:
  {{- include "localization.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose -f ../services/docker-compose.yml convert
    kompose.version: 1.28.0 (c4137012e)
spec:
  {{- if eq .Values.environment "kubernetes-athens" }}
  ingressClassName: nginx
  {{- end }}
  rules:
  - host: "{{ .Values.env.frontendAddress }}"
    http:
      paths:
      - backend:
          service:
            name: 'netapp'
            port:
              number: 8000
        path: /
        pathType: Prefix
---
apiVersion: v1
kind: Service
metadata:
  name: netapp
  labels:
    io.kompose.service: localization-netapp
  {{- include "localization.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.28.0 (c4137012e)
spec:
  type: {{ .Values.netapp.type }}
  selector:
    io.kompose.service: localization-netapp
  {{- include "localization.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.netapp.ports | toYaml | nindent 2 -}}

---
apiVersion: v1
kind: Service
metadata:
  name: netapp-udp
  labels:
    io.kompose.service-udp: localization-netapp-udp
  {{- include "localization.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.28.0 (c4137012e)
    {{- if eq .Values.environment "kubernetes-uma" }}
    metallb.universe.tf/loadBalancerIPs: 10.11.23.53
    {{- end }}
spec:
  {{- if eq .Values.environment "kubernetes-uma" }}
  type: {{ .Values.netapp.typeUdp }}
  {{- end }}
  selector:
    io.kompose.service-udp: localization-netapp-udp
  {{- include "localization.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.netapp.portsUdp | toYaml | nindent 2 -}}