apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zortenet.fullname" . }}-netapp
  labels:
    io.kompose.service: app
  {{- include "zortenet.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.28.0 (c4137012e)
spec:
  replicas: {{ .Values.netapp.replicas }}
  selector:
    matchLabels:
      io.kompose.service: app
    {{- include "zortenet.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        io.kompose.network/nef-emulator-default: "true"
        io.kompose.service: app
      {{- include "zortenet.selectorLabels" . | nindent 8 }}
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.28.0 (c4137012e)
    spec:
      imagePullSecrets:
        - name: regcred
      {{- if eq .Values.environment "kubernetes-athens" }}
      hostAliases:
        - ip: "{{ .Values.ingress_ip.athens }}"
          hostnames:
            - "{{ .Values.env.capifHostname }}"
            - "{{ .Values.env.nefAddress }}"
            - "{{ .Values.env.tsnAddress }}"
      {{- end }}
      {{- if eq .Values.environment "kubernetes-cosmote" }}
      hostAliases:
        - ip: "{{ .Values.ingress_ip.cosmote }}"
          hostnames:
            - "{{ .Values.env.capifHostname }}"
            - "{{ .Values.env.nefAddress }}"
            - "{{ .Values.env.tsnAddress }}"
      {{- end }}
      {{- if eq .Values.environment "kubernetes-uma" }}
      hostAliases:
        - ip: "{{ .Values.ingress_ip.uma }}"
          hostnames:
            - "{{ .Values.env.capifHostname }}"
            - "{{ .Values.env.nefAddress }}"
            - "{{ .Values.env.tsnAddress }}"
      {{- end }}
      containers:
      - env:
        - name: ENVIRONMENT_MODE
          value: {{ quote .Values.env.environmentMode }}
        - name: CALLBACK_ADDRESS
          value: {{ quote .Values.env.callbackAddress }}
        - name: CAPIF_HOSTNAME
          value: {{ quote .Values.env.capifHostname }}
        - name: CAPIF_PORT_HTTP
          value: {{ quote .Values.env.capifPortHttp }}
        - name: CAPIF_PORT_HTTPS
          value: {{ quote .Values.env.capifPortHttps }}
        - name: NEF_ADDRESS
          value: {{ quote .Values.env.nefAddress }}
        - name: NEF_PASSWORD
          value: {{ quote .Values.env.nefPassword }}
        - name: NEF_USER
          value: {{ quote .Values.env.nefUser }}
        - name: PATH_TO_CERTS
          value: {{ quote .Values.env.pathToCerts }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.netapp.zorteNetapp.image.repository }}-{{ .Values.netapp.zorteNetapp.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: Always
        name: zorte-netapp
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always