apiVersion: v1
kind: Service
metadata:
  name: dbnetapp
  labels:
    io.kompose.service: dbnetapp
  {{- include "fogus-kube.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.28.0 (c4137012e)
spec:
  type: {{ .Values.dbnetapp.type }}
  selector:
    io.kompose.service: dbnetapp
  {{- include "fogus-kube.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.dbnetapp.ports | toYaml | nindent 2 -}}