apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    io.kompose.service: netappdjango
  {{- include "fogus-kube.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.28.0 (c4137012e)
spec:
  type: {{ .Values.django.type }}
  selector:
    io.kompose.service: netappdjango
  {{- include "fogus-kube.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.django.ports | toYaml | nindent 2 -}}