apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose-resolved.yaml -o marketplace
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.mktp_db_service }}
  name: {{ .Values.mktp_db_service }}
spec:
  ports:
    - name: "port-db"
      port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: {{ .Values.mktp_db_service }}
status:
  loadBalancer: {}
