apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose-resolved.yaml -o marketplace
    kompose.version: 1.26.1 (HEAD)
    # helm.sh/hook: post-install
    # helm.sh/hook-weight: "5"
    # helm.sh/hook-delete-policy: hook-succeeded
  creationTimestamp: null
  labels:
    io.kompose.service:  {{ .Values.mktp_php_service }}
  name: {{ .Values.mktp_php_service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.mktp_php_service }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose-resolved.yaml -o marketplace
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/docker_evolved5g_net: "true"
        io.kompose.service: {{ .Values.mktp_php_service }}
    spec:
      containers:
      - name: {{ .Values.mktp_php_service }}
        image: "dockerhub.hi.inet/evolved-5g/marketplace/evolved5g-pilot-marketplace-laravel:{{ .Values.version }}"
        env:
            - name: APP_ROOT
              value: /var/www/html
            - name: NUM_PROCS
              value: "4"
            - name: OPTIONS
              value: --queue=mail-queue,blockchain-transactions --tries=3
            - name: QUEUE_DRIVER
              value: sync
            - name: DB_HOST
              value: {{ .Values.mktp_db_service }}
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: {{ .Values.db_name }}
            - name: DB_USERNAME
              value: {{ .Values.db_user }}
            - name: DB_PASSWORD
              value: {{ .Values.db_password }}
        ports:
          - containerPort: 80
        securityContext:
          runAsUser: 0
          allowPrivilegeEscalation: false
        resources: {}
      initContainers:
      - name: post-deploy-php
        image: "dockerhub.hi.inet/evolved-5g/marketplace/evolved5g-pilot-marketplace-laravel:{{ .Values.version }}"
        command: ["/bin/bash"]
        args:
          - -c
          - >-
              chown -R laravel:www-data * &&
              export COMPOSER_ALLOW_SUPERUSER=1 &&
              composer install &&
              composer dump-autoload &&
              php artisan key:generate &&
              php artisan migrate &&
              php artisan db:seed &&
              php artisan storage:link &&
              npm install &&
              npm run development
          # command: ["/bin/sh", "-c"]
          # args:
          #   - echo "HOLA"
          
        # - name: post-install-job
        #   image: "dockerhub.hi.inet/evolved-5g/marketplace/evolved5g_pilot_marketplace_laravel:{{ .Values.version }}"
        #   command: ["echo", "HOLA"]
        #   # command:
          #   - sh
          #   - -c 
          #   - |-
          #     OUTPUT=$(redis-cli -h redis -p 6379 -n 1 GET  server_priv_key)
          #     echo "$OUTPUT"
              # if [ -z "$OUTPUT" ]; then
              #   echo "cannot get the server public key from redis"
              #   exit 1;
              # fi

          # command: ["/bin/sh", "-c"]
          # args:
          #   - echo "HOLA"



      restartPolicy: Always


status: {}
