apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose-resolved.yaml -o marketplace
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service:  {{ .Values.mktp_blockchain_sender_service }}
  name: {{ .Values.mktp_blockchain_sender_service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.mktp_blockchain_sender_service }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose-resolved.yaml -o marketplace
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/docker_evolved5g_net: "true"
        io.kompose.service: {{ .Values.mktp_blockchain_sender_service }}
    spec:
      containers:
        - image: "dockerhub.hi.inet/evolved-5g/marketplace/evolved5g_blockchain_sender:{{ .Values.version }}"
          name: {{ .Values.mktp_blockchain_sender_service }}
          ports:
            - containerPort: 8000
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: false

      restartPolicy: Always


status: {}
