apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose-resolved.yaml -o marketplace
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service:  {{ .Values.mktp_tmf_service }}
  name: {{ .Values.mktp_tmf_service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.mktp_tmf_service }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose-resolved.yaml -o marketplace
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/docker_evolved5g_net: "true"
        io.kompose.service: {{ .Values.mktp_tmf_service }}
    spec:
      containers:
        - image: "dockerhub.hi.inet/evolved-5g/marketplace/marketplace-tmf-4.0.0:1.0"
          name: {{ .Values.mktp_tmf_service }}
          env:
            - name: MONGO_URL
              value: mongodb://{{ .Values.mktp_tmf_db_service }}:27017/
          ports:
            - containerPort: 8080
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: false

      restartPolicy: Always


status: {}
