apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose-resolved.yaml -o marketplace
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service:  {{ .Values.mktp_php_service }}
  name: {{ .Values.mktp_php_service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.mktp_php_service }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose-resolved.yaml -o marketplace
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/docker_evolved5g_net: "true"
        io.kompose.service: {{ .Values.mktp_php_service }}
    spec:
      containers:
      - name: {{ .Values.mktp_php_service }}
        image: "dockerhub.hi.inet/evolved-5g/marketplace/evolved5g-pilot-marketplace-laravel:{{ .Values.version }}"
        imagePullPolicy: Always
        env:
            - name: APP_ROOT
              value: /var/www/html
            - name: NUM_PROCS
              value: "4"
            - name: OPTIONS
              value: --queue=mail-queue,blockchain-transactions --tries=3
            - name: QUEUE_DRIVER
              value: sync
            - name: DB_HOST
              value: {{ .Values.mktp_db_service }}
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: {{ .Values.db_name }}
            - name: DB_USERNAME
              value: {{ .Values.db_user }}
            - name: DB_PASSWORD
              value: {{ .Values.db_password }}
        ports:
          - containerPort: 80
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
        volumeMounts:
            - name: mktp-php-pvc
              mountPath: /var/www/html/public/assets
        securityContext:
          runAsUser: 0
          allowPrivilegeEscalation: false
        resources: {}
      initContainers:
      - name: post-deploy-php
        image: "dockerhub.hi.inet/evolved-5g/marketplace/evolved5g-pilot-marketplace-laravel:{{ .Values.version }}"
        command: ["/bin/bash"]
        args:
          - -c
          - >-
              chown -R laravel:www-data * &&
              export COMPOSER_ALLOW_SUPERUSER=1 &&
              composer install &&
              composer dump-autoload &&
              yes | php artisan key:generate &&
              yes | php artisan migrate &&
              yes | php artisan db:seed &&
              yes | php artisan storage:link &&
              npm install &&
              npm run production
      restartPolicy: Always
      volumes:
      - name: mktp-php-pvc
        persistentVolumeClaim:
          claimName: mktp-php-pvc


status: {}
