apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose-resolved.yaml -o marketplace
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: npm
  name: npm
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: npm
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose-resolved.yaml -o marketplace
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/docker_evolved5g_net: "true"
        io.kompose.service: npm
    spec:
      containers:
        - command:
            - npm
          image: npm
          name: evolved5g-pilot-npm
          resources: {}
          workingDir: /var/www/html
      restartPolicy: Always
status: {}
