apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose-resolved.yaml -o marketplace
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: php-mktp
  name: php-mktp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: php-mktp
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose-resolved.yaml -o marketplace
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/docker_evolved5g_net: "true"
        io.kompose.service: php-mktp
    spec:
      containers:
        - image: dockerhub.hi.inet/evolved-5g/marketplace/evolved5g_pilot_marketplace_laravel:latest
          name: php-mktp
          env:
            - name: APP_ROOT
              value: /var/www/html
            - name: NUM_PROCS
              value: "4"
            - name: OPTIONS
              value: --queue=mail-queue,blockchain-transactions --tries=3
            - name: QUEUE_DRIVER
              value: sync
            - name: DATABASE_URL
              value: sync
            - name: DB_HOST
              value: db-mktp.apps.ocp-epg.hi.inet
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: {{ .Values.db_name }}
            - name: DB_USERNAME
              value: {{ .Values.db_user }}
            - name: DB_PASSWORD
              value: {{ .Values.db_password }}

          ports:
            - containerPort: 80
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: false

      restartPolicy: Always


status: {}
