apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose-resolved.yaml -o marketplace
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: php-mktp
  name: php-mktp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: php-mktp
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose-resolved.yaml -o marketplace
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/docker_evolved5g_net: "true"
        io.kompose.service: php-mktp
    spec:
      containers:
        - image: dockerhub.hi.inet/evolved-5g/marketplace/evolved5g_pilot_php:latest
          name: php-mktp
          ports:
            - containerPort: 80
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: false
          resources: {}
      restartPolicy: Always

status: {}
