apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dummy-network-application.fullname" . }}-capif-registration
  labels:
    io.kompose.service: capif-callback-server-env
  {{- include "dummy-network-application.labels" . | nindent 4 }}
data:
  capif-registration.json: |
    {
      "folder_to_store_certificates": "/usr/src/app/capif_onboarding",
      "capif_host": {{ .Values.env.capifHostname | quote }},
      "capif_http_port": {{ .Values.env.capifPortHttp | quote }},
      "capif_https_port": {{ .Values.env.capifPortHttps | quote }},
      "capif_netapp_username": "test_network_app_26",
      "capif_netapp_password": "test_network_app_password",
      "capif_callback_url": {{ .Values.env.capifCallbackUrl | quote }},
      "description": ",test_app_description",
      "csr_common_name": "test_app_common_name",
      "csr_organizational_unit": "test_app_ou",
      "csr_organization": "test_app_o",
      "crs_locality": "Madrid",
      "csr_state_or_province_name": "Madrid",
      "csr_country_name": "ES",
      "csr_email_address": "test@example.com"
    }