apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml -c -o folder
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: api-invoker-management
  name: api-invoker-management
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-invoker-management
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yaml -c -o folder
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: api-invoker-management
    spec:
      containers:
        - image: dockerhub.hi.inet/evolved-5g/capif/api_invoker_management_api:latest
          name: api-invoker-management
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /usr/src/app
              name: api-invoker-management-claim0
      restartPolicy: Always
      volumes:
        - name: api-invoker-management-claim0
          persistentVolumeClaim:
            claimName: api-invoker-management-claim0
status: {}
