apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml -c -o folder
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: jwtauth
  name: jwtauth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jwtauth
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yaml -c -o folder
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: jwtauth
    spec:
      containers:
        - image: dockerhub.hi.inet/evolved-5g/jwtauth:latest
          name: jwtauth
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
