releases:
  - name: capif
    chart: ../capif/
    namespace: ""
    atomic: true
    wait: true
    values: 
      - ../capif/values.yaml
      - nginx:
            nginx:
              env:
                capifHostname: ""