releases:
  - name: fogus
    chart: ../fogus/
    namespace: ""
    atomic: true
    wait: true
    values: 
      - ../fogus-kube/values.yaml
      - env:
          fogusHostname: ""
          environment: ""
      - fe:
          replicas: 