apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml -c -o folder
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: api-provider-management
  name: api-provider-management
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-provider-management
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yaml -c -o folder
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: api-provider-management
    spec:
      containers:
        - image: "dockerhub.hi.inet/evolved-5g/capif/services_api-provider-management_1:{{ .Values.version }}"
          name: api-provider-management
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
