apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml -c -o folder
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: logs
  name: logs
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logs
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yaml -c -o folder
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: logs
    spec:
      containers:
        - image: dockerhub.hi.inet/evolved-5g/capif/auditing_api:latest
          name: logs
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
