apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml -c -o folder
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: easy-rsa
  name: easy-rsa
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: easy-rsa
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yaml -c -o folder
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: easy-rsa
    spec:
      containers:
        - image: "dockerhub.hi.inet/evolved-5g/capif/services_easy-rsa_1:{{ .Values.version }}"
          name: easy-rsa
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
