{{- if ne .Values.version "2.1" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml -c -o folder
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yaml -c -o folder
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: redis
    spec:
      containers:
        - image: "dockerhub.hi.inet/evolved-5g/capif/services_redis_1:{{ .Values.version }}"
          command:
          - redis-server
          name: redis
          env:
            - name: REDIS_REPLICATION_MODE
              value: master
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
status: {}

{{ else }}
# Default case
{{- end }}