apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o dummy-netapp
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: cafa-netapp
  name: inin-netapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cafa-netapp
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -o dummy-netapp
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: cafa-netapp
    spec:
      containers:
        - image: dockerhub.hi.inet/evolved-5g/validation/cafatechnetapp3/cafatechnetapp3-cafatech-netapp-3:latest
          env:
              # NetApp variables
            - name: NETAPP_NAME
              value: CafaTechNetApp3
            - name: NETAPP_ID
              value: CAFA-NetApp-3
            - name: NETAPP_IP
              value: cafa.apps.ocp-epg.hi.inet
            - name: SERVER_FOR_VAPP
              value: 127.0.0.1:9877
            - name: CALLBACK_ADDRESS
              value: cafa.apps.ocp-epg.hi.inet/nefcallbacks
            - name: FRONTEND_CALLBACK_ADDRESS
              value: cafa.apps.ocp-epg.hi.inet
            # NEF variables (when NetApp is Dockerized)
            - name: NEF_USER
              value: admin@my-email.com
            - name: NEF_PASSWORD
              value: pass
            - name: NEF_ADDRESS
              value: evol5-capif-nef.apps.ocp-epg.hi.inet
            # CAPIF variables
            - name: CAPIF_HOSTNAME
              value: capif.apps.ocp-epg.hi.inet
            - name: CAPIF_PORT_HTTP
              value: "80"
            - name: CAPIF_PORT_HTTPS
              value: "443"
            - name: PATH_TO_CERTS
              value: certificates
            # Netapp to CAPIF credentials
            - name: NETAPP_USER
              value: netapp_user
            - name: NETAPP_PASS
              value: netapp_pass
          name: cafa-netapp
          ports:
            - containerPort: 5555
          resources: {} 
      restartPolicy: Always
status: {}
