
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netapp
  labels:
  {{- include "inin.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose -f ../services/docker-compose.yml convert
    kompose.version: 1.28.0 (c4137012e)
spec:
  {{- if or (eq .Values.environment "kubernetes-athens") (eq .Values.environment "kubernetes-cosmote") }}
  ingressClassName: nginx
  {{- end }}
  rules:
  - host: "{{ .Values.env.frontendAddress }}"
    http:
      paths:
      - backend:
          service:
            name: 'rmonnetapp'
            port:
              number: 80
        path: /
        pathType: Prefix
---

apiVersion: v1
kind: Service
metadata:
  name: rmonnetapp
  labels:
    io.kompose.service: rmonnetapp
  {{- include "inin.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml convert
    kompose.version: 1.28.0 (c4137012e)
spec:
  type: {{ .Values.netapp.type }}
  selector:
    io.kompose.service: rmonnetapp
  {{- include "inin.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.netapp.ports | toYaml | nindent 2 -}}