apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o fogus
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: iqbcallbacks
  name: iqbcallbacks
spec:
  replicas: {{ .Values.app_replicas }}
  selector:
    matchLabels:
      io.kompose.service: iqbcallbacks
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -o fogus
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: iqbcallbacks
    spec:
      containers:
        - name: iqbcallbacks
          image: dockerhub.hi.inet/evolved-5g/iqb-netapp/iqb-netapp-callbacks:latest
          ports:
            - containerPort: 5002
          resources: {}
      restartPolicy: Always
status: {}
