apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o fogus
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: iqbcallbacks
  name: iqbcallbacks
spec:
  ports:
    - name: "iqbcallbacks-port"
      port: 5002
      targetPort: 5002
  selector:
    io.kompose.service: iqbcallbacks
status:
  loadBalancer: {}
