apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    io.kompose.service: keycloak
  {{- include "iqb.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.28.0 (c4137012e)
spec:
  type: {{ .Values.keycloak.type }}
  selector:
    io.kompose.service: keycloak
  {{- include "iqb.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.keycloak.ports | toYaml | nindent 2 -}}