apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tsn-frontend.fullname" . }}-configmap
data:
  {{- with (first .Values.ingress.hosts) }}
  config.json: |
    {
      "BackEnd": null,
      "FrontEnd": {
        "DomainName": "{{ default "tsn.apps.ocp-epg.hi.inet" .host }}"
      },
      "CAPIF": {
        "Enabled": {{ default "true" .Values.configMap.capifEnabled }},
        "SecurityEnabled": {{ default "true" .Values.configMap.capifSecurityEnabled }},
        "LoggingEnabled": {{ default "true" .Values.configMap.capifLoggingEnabled }},
        "Host": "{{ .Values.configMap.capifHostname }}",
        "HttpPort": {{ .Values.configMap.capifPortHttp }},
        "HttpsPort": {{ .Values.configMap.capifPortHttps }}
      }
    }
  {{- end }}