apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tsn-frontend.fullname" . }}-configmap
data:
  config.json: |
    {
      "BackEnd": null,
      "FrontEnd": {
        "DomainName": {{ include "tsn-frontend.fullname" . }}
      },
      "CAPIF": {
        "Enabled": {{ default "true" .Values.configMap.capifEnabled }},
        "SecurityEnabled": {{ default "true" .Values.configMap.capifSecurityEnabled }},
        "LoggingEnabled": {{ default "true" .Values.configMap.capifLoggingEnabled }},
        "Host": "{{ .Values.configMap.capifHostname }}",
        "HttpPort": {{ .Values.configMap.capifPortHttp }},
        "HttpsPort": {{ .Values.configMap.capifPortHttps }}
      }
    }