apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tsn-frontend.fullname" . }}
  labels:
    {{- include "tsn-frontend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tsn-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "tsn-frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if eq .Values.environment "kubernetes-athens" }}
      hostAliases:
        - ip: "{{ .Values.ingress_ip.athens }}"
          hostnames:
            - "{{ .Values.nginx.nginx.env.capifHostname }}"
      {{- end }}
      {{- if eq .Values.env "kubernetes-uma" }}
      hostAliases: 
        - ip: "{{ .Values.ingress_ip.uma }}"
          hostnames:
            - "{{ .Values.nginx.nginx.env.capifHostname }}"
      {{- end }}
      serviceAccountName: {{ include "tsn-frontend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}-{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: frontend-port
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port:  frontend-port
          readinessProbe:
            httpGet:
              path: /
              port:  frontend-port
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: {{ include "tsn-frontend.fullname" . }}-config
            mountPath: "/srv/tsn_af/config.json"
            subPath: config.json
      volumes:
      - name: {{ include "tsn-frontend.fullname" . }}-config
        configMap:
          name: {{ include "tsn-frontend.fullname" . }}-configmap
          items:
          - key: "config.json"
            path: "config.json"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
