apiVersion: v1
kind: Service
metadata:
  name: {{ include "tsn-frontend.fullname" . }}
  labels:
    {{- include "tsn-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: frontend-port
  selector:
    {{- include "tsn-frontend.selectorLabels" . | nindent 4 }}
