# helmfile sync -f helmfile.yaml

helmDefaults:
  createNamespace: true
  force: true
  timeout: 600

repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
  
releases:
  - name: prometheus
    chart: ../prometheus/
    namespace: prometheus
#    atomic: true
    wait: true
    timeout: 600
    values:
      - ./values.yaml
      - prometheus:
          ingress:
            hosts:
              - host: prometheus.mon.int
                paths:
                  - path: /
                    pathType: Prefix
  - name: monitoring
    namespace: prometheus
    chart: prometheus-community/kube-state-metrics
