apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o dummy-aef
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: capif-callback-server
  name: capif-callback-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: capif-callback-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -o dummy-aef
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/demo-network: "true"
        io.kompose.service: capif-callback-server
    spec:
      containers:
        - env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
          image: dockerhub.hi.inet/evolved-5g/dummy-aef/dummy-aef-dummy-aef_capif_callback_server_1:latest
          name: capif-callback-server
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always

status: {}
