apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o dummy-aef
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: python-aef
  name: python-aef
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: python-aef
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -o dummy-aef
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/demo-network: "true"
        io.kompose.service: python-aef
    spec:
      containers:
        - env:
            - name: CAPIF_HOSTNAME
            - name: CAPIF_PORT
              value: "8080"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: REQUESTS_CA_BUNDLE
              value: /usr/src/app/ca.crt
            - name: SSL_CERT_FILE
              value: /usr/src/app/ca.crt
          image: python_aef
          name: python-aef
          resources: {}
          volumeMounts:
            - mountPath: /usr/src/app
              name: python-aef-claim0
      hostname: exposer
      restartPolicy: Always
      volumes:
        - name: python-aef-claim0
          persistentVolumeClaim:
            claimName: python-aef-claim0
status: {}
