# -- The Environment variable. It accepts: 'kuberentes-athens', 'kuberentes-uma', 'openshift'
environment: "openshift"

# pipeline. It accepts: validation, certification or verification
pipeline: certification

# -- If env: 'kuberentes-athens' or env: 'kuberentes-uma', use the Ip address dude for the kubernetes to your Ingress Controller ej: kubectl -n NAMESPACE_CAPIF get ing s
ingress_ip: 
    athens: "10.161.1.126"
    uma: "10.11.23.49"
    cosmote: "172.25.2.100"

db:
  ports:
  - name: "db-port"
    port: 5432
    targetPort: 5432
  postgresContainer:
    image:
      # -- The docker image tag to use
      # -- @default Chart version
      tag: "umacsicnetapp-postgres_container"
  replicas: 1
  type: ClusterIP
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 128Mi
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

env:
  environmentMode: production
  frontendAddress: my-umacsic.apps.ocp-epg.hi.inet
  callbackAddress: ""
  capifHostname: my-capif.apps.ocp-epg.hi.inet
  capifPortHttp: 30048
  capifPortHttps: 30548
  error404Help: "False"
  flaskApp: main.py
  nefAddress: my-nef.apps.ocp-epg.hi.inet
  pathToCerts: /usr/src/app/certs
  pgdata: /var/lib/postgresql/data
  postgresDb: netappdb
  postgresHostname: db
  postgresPort: 5432
  postgresUser: netapp
  postgresPassword: secret
  secretKey: 7110c8ae51a4b5af97be6534caefs0e4bb9bdcb3380af00sr50b23a5d1616bf319bc298105da20fe
  showSqlalchemyLogMessages: "False"
  sqlalchemyTrackModifications: "False"
  tsnAddress: my-tsn.apps.ocp-epg.hi.inet

netapp:
  netapp:
    image:
      # -- The docker image tag to use
      # -- @default Chart version
      tag: "umacsicnetapp-netapp"
  ports:
  - name: "netapp-port"
    port: 10001
    targetPort: 10001
  replicas: 1
  type: ClusterIP
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 128Mi
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

kubernetesClusterDomain: cluster.local