## variables for the CAPIF
nef_host: http://evol5-capif-nef.apps.ocp-epg.hi.inet
host_front: immersion-web-controller.apps.ocp-epg.hi.inet
netappid: immnetapp
netapp_name: IMMNetapp
netapp_ip: "http://0.0.0.0"
vapp_ip: "127.0.0.1"
netapp_port_5g: 9999
netapp_port_web: 9988
netapp_port_vapp: 9986
env: openshift