apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o dummy-netapp
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: callback-dummy
  name: callback-dummy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: callback-dummy
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -o dummy-netapp
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: callback-dummy
    spec:
    {{- if or (eq .Values.env "kubernetes-athens") (eq .Values.env "kubernetes-uma") }}
      imagePullSecrets:
        - name: regcred
      {{- end }}
      containers:
        {{- if or (eq .Values.env "kubernetes-athens") (eq .Values.env "kubernetes-uma") }}
        - image: 709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:dummy-netapp_capif_callback_server_1-latest
        {{- else }}
        - image: dockerhub.hi.inet/evolved-5g/dummy-netapp/dummy-netapp_capif_callback_server_1:latest
        {{- end }}
          name: callback-dummy
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
