apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o dummy-aef
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: callback-dummy
  name: callback-dummy
spec:
  ports:
    - name: "port-callbkac-dummy"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: callback-dummy
status:
  loadBalancer: {}
