apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o dummy-aef
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: redis-aef
  name: redis-aef
spec:
  ports:
    - name: "port-redis"
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: redis-aef
status:
  loadBalancer: {}
